### ISSUE TITLE
Rename repository

### ISSUE THREAD

**Issue by alrra** [sonarwhal/sonarwhal-rule-template#2]
From: https://github.com/sonarwhal/sonarwhal-rule-template/pull/1#issuecomment-331687522

> I'm thinking that maybe this project (and npm package) should be @sonarwhal/rule-template.
Thoughts?

@molant Are we going to include any other templates in this repository (e.g.: one for formatters)?

**Comment by molant** [comment]
> Are we going to include any other templates in this repository (e.g.: one for formatters)?

I was thinking on having separate projects for each thing so it is easier to know where things are and what needs to be copied during the creation process.

**Comment by alrra** [comment]
Then, let's go with `rule-template`.
